apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: florian-lutz-express-sample-app-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express-sample-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/florian-lutz-express-pipeline
    - name: image-repo
      value: quay.io/fluxens0/express-sample-app
  pipelineRef:
    name: express
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: gitops-repository
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: git-credentials
      secret:
        secretName: git-credentials
